<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
* Class RomSeeder (Seeder)
* 
* @author Hugo Silva Benitez <hsilben979@g.educaand.es>
* @date 2026-05-05
* 
* This seeder populates the ROM catalog with the default games.
*/
class RomSeeder extends Seeder
{
    public function run(): void
    {
        $emulatorId = DB::table('emulators')->where('name', 'GBA.js 2')->value('id');

        if (!$emulatorId) {
            $emulatorId = DB::table('emulators')->insertGetId([
                'name' => 'GBA.js 2',
                'version' => '1.0',
                'wasm_path' => 'public/emulator/gbajs2',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::table('roms')->upsert([
            [
                'title' => 'Advance Wars',
                'slug' => 'advance-wars',
                'description' => 'Estrategia por turnos ideal para un catalogo variado y partidas tacticas.',
                'file_path' => 'roms/advance-wars.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Advance Wars 2: Black Hole Rising',
                'slug' => 'advance-wars-2-black-hole-rising',
                'description' => 'Secuela muy solida para quienes quieran engancharse mas horas al sistema.',
                'file_path' => 'roms/advance-wars-2-black-hole-rising.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Castlevania: Aria of Sorrow',
                'slug' => 'castlevania-aria-of-sorrow',
                'description' => 'Una opcion fuerte de accion y exploracion para dar variedad al catalogo.',
                'file_path' => 'roms/castlevania-aria-of-sorrow.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fire Emblem',
                'slug' => 'fire-emblem',
                'description' => 'Rol tactico muy reconocible y perfecto para jugadores que buscan progresion.',
                'file_path' => 'roms/fire-emblem.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Golden Sun',
                'slug' => 'golden-sun',
                'description' => 'RPG clasico para cubrir el perfil de aventura larga con narrativa.',
                'file_path' => 'roms/golden-sun.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Golden Sun: The Lost Age',
                'slug' => 'golden-sun-the-lost-age',
                'description' => 'Complementa muy bien el catalogo si quieres dos RPG largos y potentes.',
                'file_path' => 'roms/golden-sun-the-lost-age.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kirby & the Amazing Mirror',
                'slug' => 'kirby-and-the-amazing-mirror',
                'description' => 'Aventura ligera y accesible para equilibrar el catalogo.',
                'file_path' => 'roms/kirby-and-the-amazing-mirror.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mario & Luigi: Superstar Saga',
                'slug' => 'mario-and-luigi-superstar-saga',
                'description' => 'RPG muy amigable para jugadores nuevos y muy valioso en una seleccion cerrada.',
                'file_path' => 'roms/mario-and-luigi-superstar-saga.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mario Kart: Super Circuit',
                'slug' => 'mario-kart-super-circuit',
                'description' => 'Cubre carreras arcade y partidas rapidas dentro del navegador.',
                'file_path' => 'roms/mario-kart-super-circuit.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Metroid Fusion',
                'slug' => 'metroid-fusion',
                'description' => 'Accion y exploracion con identidad muy clara para el catalogo.',
                'file_path' => 'roms/metroid-fusion.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Metroid: Zero Mission',
                'slug' => 'metroid-zero-mission',
                'description' => 'Otra gran pieza de accion para reforzar la seccion de aventuras.',
                'file_path' => 'roms/metroid-zero-mission.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pokemon Emerald',
                'slug' => 'pokemon-emerald',
                'description' => 'Muy buena opcion si quieres un RPG largo y muy reconocible.',
                'file_path' => 'roms/pokemon-emerald.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pokemon FireRed',
                'slug' => 'pokemon-firered',
                'description' => 'Uno de los juegos mas atractivos para una primera demo de la plataforma.',
                'file_path' => 'roms/pokemon-firered.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Legend of Zelda: The Minish Cap',
                'slug' => 'the-legend-of-zelda-the-minish-cap',
                'description' => 'Aventura muy redonda para cubrir el genero mas clasico del sistema.',
                'file_path' => 'roms/the-legend-of-zelda-the-minish-cap.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wario Land 4',
                'slug' => 'wario-land-4',
                'description' => 'Plataformas con mucha personalidad y ritmo rapido.',
                'file_path' => 'roms/wario-land-4.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'WarioWare, Inc.: Mega Microgame$!',
                'slug' => 'warioware-inc-mega-microgames',
                'description' => 'Microjuegos perfectos para sesiones cortas en navegador.',
                'file_path' => 'roms/warioware-inc-mega-microgames.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => $emulatorId,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Yoshi\'s Island: Super Mario Advance 3',
                'slug' => 'yoshis-island-super-mario-advance-3',
                'description' => 'Plataformas accesible y muy vistoso para completar la seleccion de 15.',
                'file_path' => 'roms/yoshis-island-super-mario-advance-3.gba',
                'cover_image' => null,
                'size_bytes' => null,
                'region' => 'USA',
                'emulator_id' => 1,
                'uploaded_by' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ], ['slug'], [
            'title',
            'description',
            'file_path',
            'cover_image',
            'size_bytes',
            'region',
            'emulator_id',
            'uploaded_by',
            'is_public',
            'updated_at',
        ]);
    }
}
